### ISSUE TITLE
Submenu freeze

### ISSUE THREAD

**Issue by DjaiGM** [LuigiBlood/zelda_dawn_dusk#3]
I'm getting freezes after opening the submenu for several times.
Normal OOT is working fine.
Tried it with v1.0 and 1.1.
This happens on PJ64 2.3.2 / Glide64 4.0 Public Release

**Comment by LuigiBlood** [comment]
Which version of the mod are you playing?

**Comment by DjaiGM** [comment]
The Patch version(with U 1.0 and 1.1). Also tried the 64DD version wich seems to work fine.

**Comment by LuigiBlood** [comment]
Did you try the v2.0 mod release?

**Comment by DjaiGM** [comment]
hmmm hard to say, i reinstalled everything(emulator, plugins, repatched with 2.0, new savegame...) and now everything is working fine

**Comment by Rus3545** [comment]
Hello.
(U) (V1.0)
The text breaks off very suddenly at the 2088 dialogue. nes_message_data_static.ztxt is over.
The end of line "02" is not visible, and there are still quite a few pointers ...
Probably they are not used, but still, what should be the last sentence?
```
VROM: 00B88B24: 2088 dialogue - 71970000 070380F0:    
"You shouldn't be so picky about
what you eat! Do you eat all you"
```
Although, according to the pointers, there should still be a lot of text ...   
`VROM: 00B88C64: 2128 dialogue - FFFD0000 070387CC`

**Comment by LuigiBlood** [comment]
I would have suggested doing a new issue about it but I don't think this is used. The text is based on the original with replacements so you might get cutoffs like that.

**Comment by Rus3545** [comment]
Probably, but this is not the issue of this mod.
Although here this question does not belong ... Dilemma.
I understand that it is based on the original, the logic of the replacements is not clear to me. Many original structures are used, but very strange. The number of pointers has clearly become larger and the text of the text contains the caption of the hack development team (twice, in separate lines and all in one dialog). 
```
[instant]Lead Development & Music
[spc:37]CAPTAIN SEEDY-EYE

64DD Porting
[spc:37]LUIGIBLOOD

Special Thanks to
[spc:37]PK-LOVE
[spc:37]BWXIX

[spc:07]For more mods like this, visit
[/instant]/0E/C8
```
But how to determine which sentence is the last if it is not identified by FFFD0000 & FFFF0000 and unused text is left?

P.S:
I'm usually interested in the hacks Zelda64 technical implementation of the possibility of translating them into other languages. For example, hack MM_MQ by DeathBasket can be easily translated, it’s more difficult to fix it, hacks Aroenai, such as GCtoN64, too, although it’s also very difficult to find the author’s errors.

But here it is already difficult to find resources, although they remained in their places, but the logic of their replacement is completely incomprehensible.
I wrote about the text above, now about the langpack_graphics: something in place of Japanese, something English, something both there and there (it's about textures) ...

**Comment by LuigiBlood** [comment]
Please make another issue at this point if you want to discuss this, I'll talk about it to the lead dev in the meantime.
