### ISSUE TITLE
Rainbow static

### ISSUE THREAD

**Issue by Aaquin** [LuigiBlood/zelda_dawn_dusk#5]
Every time I try to walk into the door in the forest or try to grab the metal shield my screen turns into a Rainbow colored static
I am using Project64 2.4.0.976-g5ac358a
Graphics driver is GlideN64 Public release 4
all other drivers are default.
 I am not using any textures
![Dawn   Dusk](https://user-images.githubusercontent.com/55778454/65571622-9ac51480-df22-11e9-9958-0b50e6d873e4.png)

**Comment by LuigiBlood** [comment]
Which version of the mod are you using? v1.0, v2.0? Which Zelda version? Disk or Standalone ROM patch?

**Comment by Aaquin** [comment]
2.0 of the mod 1.0 of Zelda

**Comment by LuigiBlood** [comment]
Can you try out the latest Project64 build on 64dd.org? I'm honestly not sure why it does this and I had people where it just didn't happen on that build.

**Comment by Aaquin** [comment]
i just tried the latest build with the patched version and it did the same thing. I changed to loading the game with the disc and it works fine

**Comment by LuigiBlood** [comment]
I have genuinely no clue why this happens you're the only one I think

**Comment by Aaquin** [comment]
well this project is still in development and i cant imagine modding like this is perfect yet. Got it working though and planning on having fun. hope to see more in the future
